org.gradle.jvmargs = -Xmx2G
org.gradle.daemon = false

# Project
version = 0.0.10
group = com.github.mahmudindev.mcmod.dimensionfixer
description = Fix hardcoded behavior of dimension mainly for custom dimension.

mod_id = dimensionfixer
mod_name = Dimension Fixer
mod_authors = mahmudindev
mod_license = ARR

# General
java_version = 25
minecraft_version = 26.3

neoforge_loom_version = 2.0.147
neoforge_neoform_version = 1

# Fabric
fabric_loom_version = 1.18.2
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0

# NeoForge
neoforge_version = 26.3.0.10-beta
neoforge_version_range = [26.3,)
neoforge_loader_version_range = [4,)
