modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-dimensionlink/issues"
license = "ARR"

[[mods]]
modId = "dimensionfixer"
version = "${version}"
displayName = "Dimension Fixer"
authors = "mahmudindev"
description = '''
Fix hardcoded behavior of dimension mainly for custom dimension.
'''
logoFile = "assets/dimensionfixer/icon.png"

[[dependencies.dimensionfixer]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimensionfixer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "dimensionfixer.mixins.json"

["lithium:options"]
"mixin.ai.poi.fast_portals" = false
